fragment HomeParts on Home {
  __typename
  heroEyebrow
  heroTitle1
  heroTitleHighlight
  heroTitle2
  heroDescription
  heroPrimaryButton
  heroSecondaryButton
  stats {
    __typename
    value
    label
    icon
  }
  clienteleEyebrow
  clienteleTitle
  clients {
    __typename
    name
    logo
  }
}

fragment AboutParts on About {
  __typename
  eyebrow
  title1
  titleHighlight
  title2
  paragraph1
  paragraph2
  paragraph3
  image
}

fragment ContactParts on Contact {
  __typename
  eyebrow
  title
  titleHighlight
  subtitle
  mapUrl
  contactCards {
    __typename
    icon
    title
    lines
  }
  footerText1
  footerText2
  stats {
    __typename
    icon
    value
    label
  }
}

fragment GalleryParts on Gallery {
  __typename
  eyebrow
  title
  images {
    __typename
    image
    thumb
    alt
  }
}

fragment ModelsParts on Models {
  __typename
  eyebrow
  title
  description
  ctaText
  ctaLink
  models {
    __typename
    name
    title
    image
  }
}

fragment NavbarParts on Navbar {
  __typename
  navLinks {
    __typename
    name
    path
  }
  socialLinks {
    __typename
    platform
    url
  }
  ctaText
  ctaLink
}

fragment FooterParts on Footer {
  __typename
  description
  quickLinks {
    __typename
    label
    url
  }
  email
  phone
  location
  copyright
  legalLinks {
    __typename
    label
    url
  }
}

fragment EventsParts on Events {
  __typename
  title
  subtitle
  images
}

fragment Event_sectionsParts on Event_sections {
  __typename
  eyebrow
  title
  description
  start
  end
  footer
  items
}
