//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  /** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  pages: Pages;
  pagesConnection: PagesConnection;
  globals: Globals;
  globalsConnection: GlobalsConnection;
  events: Events;
  eventsConnection: EventsConnection;
  event_sections: Event_Sections;
  event_sectionsConnection: Event_SectionsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPagesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
};


export type QueryGlobalsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGlobalsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlobalsFilter>;
};


export type QueryEventsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventsFilter>;
};


export type QueryEvent_SectionsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEvent_SectionsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Event_SectionsFilter>;
};

export type DocumentFilter = {
  pages?: InputMaybe<PagesFilter>;
  globals?: InputMaybe<GlobalsFilter>;
  events?: InputMaybe<EventsFilter>;
  event_sections?: InputMaybe<Event_SectionsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = PagesHome | PagesAbout | PagesContact | PagesGallery | PagesModels | GlobalsNavbar | GlobalsFooter | Events | Event_Sections | Folder;

export type PagesHomeStats = {
  __typename?: 'PagesHomeStats';
  value?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
};

export type PagesHomeClients = {
  __typename?: 'PagesHomeClients';
  name?: Maybe<Scalars['String']['output']>;
  logo?: Maybe<Scalars['String']['output']>;
};

export type PagesHome = Node & Document & {
  __typename?: 'PagesHome';
  heroEyebrow?: Maybe<Scalars['String']['output']>;
  heroTitle1?: Maybe<Scalars['String']['output']>;
  heroTitleHighlight?: Maybe<Scalars['String']['output']>;
  heroTitle2?: Maybe<Scalars['String']['output']>;
  heroDescription?: Maybe<Scalars['String']['output']>;
  heroPrimaryButton?: Maybe<Scalars['String']['output']>;
  heroSecondaryButton?: Maybe<Scalars['String']['output']>;
  stats?: Maybe<Array<Maybe<PagesHomeStats>>>;
  clienteleEyebrow?: Maybe<Scalars['String']['output']>;
  clienteleTitle?: Maybe<Scalars['String']['output']>;
  clients?: Maybe<Array<Maybe<PagesHomeClients>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PagesAbout = Node & Document & {
  __typename?: 'PagesAbout';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title1?: Maybe<Scalars['String']['output']>;
  titleHighlight?: Maybe<Scalars['String']['output']>;
  title2?: Maybe<Scalars['String']['output']>;
  paragraph1?: Maybe<Scalars['String']['output']>;
  paragraph2?: Maybe<Scalars['String']['output']>;
  paragraph3?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PagesContactContactCards = {
  __typename?: 'PagesContactContactCards';
  icon?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  lines?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type PagesContactStats = {
  __typename?: 'PagesContactStats';
  icon?: Maybe<Scalars['String']['output']>;
  value?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type PagesContact = Node & Document & {
  __typename?: 'PagesContact';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  titleHighlight?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  mapUrl?: Maybe<Scalars['String']['output']>;
  contactCards?: Maybe<Array<Maybe<PagesContactContactCards>>>;
  footerText1?: Maybe<Scalars['String']['output']>;
  footerText2?: Maybe<Scalars['String']['output']>;
  stats?: Maybe<Array<Maybe<PagesContactStats>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PagesGalleryImages = {
  __typename?: 'PagesGalleryImages';
  image?: Maybe<Scalars['String']['output']>;
  thumb?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type PagesGallery = Node & Document & {
  __typename?: 'PagesGallery';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  images?: Maybe<Array<Maybe<PagesGalleryImages>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PagesModelsModels = {
  __typename?: 'PagesModelsModels';
  name?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type PagesModels = Node & Document & {
  __typename?: 'PagesModels';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  ctaText?: Maybe<Scalars['String']['output']>;
  ctaLink?: Maybe<Scalars['String']['output']>;
  models?: Maybe<Array<Maybe<PagesModelsModels>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Pages = PagesHome | PagesAbout | PagesContact | PagesGallery | PagesModels;

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PagesHomeStatsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PagesHomeClientsFilter = {
  name?: InputMaybe<StringFilter>;
  logo?: InputMaybe<ImageFilter>;
};

export type PagesHomeFilter = {
  heroEyebrow?: InputMaybe<StringFilter>;
  heroTitle1?: InputMaybe<StringFilter>;
  heroTitleHighlight?: InputMaybe<StringFilter>;
  heroTitle2?: InputMaybe<StringFilter>;
  heroDescription?: InputMaybe<StringFilter>;
  heroPrimaryButton?: InputMaybe<StringFilter>;
  heroSecondaryButton?: InputMaybe<StringFilter>;
  stats?: InputMaybe<PagesHomeStatsFilter>;
  clienteleEyebrow?: InputMaybe<StringFilter>;
  clienteleTitle?: InputMaybe<StringFilter>;
  clients?: InputMaybe<PagesHomeClientsFilter>;
};

export type PagesAboutFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title1?: InputMaybe<StringFilter>;
  titleHighlight?: InputMaybe<StringFilter>;
  title2?: InputMaybe<StringFilter>;
  paragraph1?: InputMaybe<StringFilter>;
  paragraph2?: InputMaybe<StringFilter>;
  paragraph3?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type PagesContactContactCardsFilter = {
  icon?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  lines?: InputMaybe<StringFilter>;
};

export type PagesContactStatsFilter = {
  icon?: InputMaybe<StringFilter>;
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type PagesContactFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  titleHighlight?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  mapUrl?: InputMaybe<StringFilter>;
  contactCards?: InputMaybe<PagesContactContactCardsFilter>;
  footerText1?: InputMaybe<StringFilter>;
  footerText2?: InputMaybe<StringFilter>;
  stats?: InputMaybe<PagesContactStatsFilter>;
};

export type PagesGalleryImagesFilter = {
  image?: InputMaybe<ImageFilter>;
  thumb?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type PagesGalleryFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  images?: InputMaybe<PagesGalleryImagesFilter>;
};

export type PagesModelsModelsFilter = {
  name?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type PagesModelsFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  ctaText?: InputMaybe<StringFilter>;
  ctaLink?: InputMaybe<StringFilter>;
  models?: InputMaybe<PagesModelsModelsFilter>;
};

export type PagesFilter = {
  home?: InputMaybe<PagesHomeFilter>;
  about?: InputMaybe<PagesAboutFilter>;
  contact?: InputMaybe<PagesContactFilter>;
  gallery?: InputMaybe<PagesGalleryFilter>;
  models?: InputMaybe<PagesModelsFilter>;
};

export type PagesConnectionEdges = {
  __typename?: 'PagesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pages>;
};

export type PagesConnection = Connection & {
  __typename?: 'PagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PagesConnectionEdges>>>;
};

export type GlobalsNavbarNavLinks = {
  __typename?: 'GlobalsNavbarNavLinks';
  name?: Maybe<Scalars['String']['output']>;
  path?: Maybe<Scalars['String']['output']>;
};

export type GlobalsNavbarSocialLinks = {
  __typename?: 'GlobalsNavbarSocialLinks';
  platform?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type GlobalsNavbar = Node & Document & {
  __typename?: 'GlobalsNavbar';
  navLinks?: Maybe<Array<Maybe<GlobalsNavbarNavLinks>>>;
  socialLinks?: Maybe<Array<Maybe<GlobalsNavbarSocialLinks>>>;
  ctaText?: Maybe<Scalars['String']['output']>;
  ctaLink?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GlobalsFooterQuickLinks = {
  __typename?: 'GlobalsFooterQuickLinks';
  label?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type GlobalsFooterLegalLinks = {
  __typename?: 'GlobalsFooterLegalLinks';
  label?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type GlobalsFooter = Node & Document & {
  __typename?: 'GlobalsFooter';
  description?: Maybe<Scalars['String']['output']>;
  quickLinks?: Maybe<Array<Maybe<GlobalsFooterQuickLinks>>>;
  email?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  copyright?: Maybe<Scalars['String']['output']>;
  legalLinks?: Maybe<Array<Maybe<GlobalsFooterLegalLinks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Globals = GlobalsNavbar | GlobalsFooter;

export type GlobalsNavbarNavLinksFilter = {
  name?: InputMaybe<StringFilter>;
  path?: InputMaybe<StringFilter>;
};

export type GlobalsNavbarSocialLinksFilter = {
  platform?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type GlobalsNavbarFilter = {
  navLinks?: InputMaybe<GlobalsNavbarNavLinksFilter>;
  socialLinks?: InputMaybe<GlobalsNavbarSocialLinksFilter>;
  ctaText?: InputMaybe<StringFilter>;
  ctaLink?: InputMaybe<StringFilter>;
};

export type GlobalsFooterQuickLinksFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type GlobalsFooterLegalLinksFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type GlobalsFooterFilter = {
  description?: InputMaybe<StringFilter>;
  quickLinks?: InputMaybe<GlobalsFooterQuickLinksFilter>;
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  copyright?: InputMaybe<StringFilter>;
  legalLinks?: InputMaybe<GlobalsFooterLegalLinksFilter>;
};

export type GlobalsFilter = {
  navbar?: InputMaybe<GlobalsNavbarFilter>;
  footer?: InputMaybe<GlobalsFooterFilter>;
};

export type GlobalsConnectionEdges = {
  __typename?: 'GlobalsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Globals>;
};

export type GlobalsConnection = Connection & {
  __typename?: 'GlobalsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GlobalsConnectionEdges>>>;
};

export type Events = Node & Document & {
  __typename?: 'Events';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  images?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type EventsFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  images?: InputMaybe<ImageFilter>;
};

export type EventsConnectionEdges = {
  __typename?: 'EventsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Events>;
};

export type EventsConnection = Connection & {
  __typename?: 'EventsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EventsConnectionEdges>>>;
};

export type Event_Sections = Node & Document & {
  __typename?: 'Event_sections';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  start?: Maybe<Scalars['String']['output']>;
  end?: Maybe<Scalars['String']['output']>;
  footer?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Event_SectionsFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  start?: InputMaybe<StringFilter>;
  end?: InputMaybe<StringFilter>;
  footer?: InputMaybe<StringFilter>;
  items?: InputMaybe<StringFilter>;
};

export type Event_SectionsConnectionEdges = {
  __typename?: 'Event_sectionsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Event_Sections>;
};

export type Event_SectionsConnection = Connection & {
  __typename?: 'Event_sectionsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Event_SectionsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePages: Pages;
  createPages: Pages;
  updateGlobals: Globals;
  createGlobals: Globals;
  updateEvents: Events;
  createEvents: Events;
  updateEvent_sections: Event_Sections;
  createEvent_sections: Event_Sections;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationCreatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationUpdateGlobalsArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalsMutation;
};


export type MutationCreateGlobalsArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalsMutation;
};


export type MutationUpdateEventsArgs = {
  relativePath: Scalars['String']['input'];
  params: EventsMutation;
};


export type MutationCreateEventsArgs = {
  relativePath: Scalars['String']['input'];
  params: EventsMutation;
};


export type MutationUpdateEvent_SectionsArgs = {
  relativePath: Scalars['String']['input'];
  params: Event_SectionsMutation;
};


export type MutationCreateEvent_SectionsArgs = {
  relativePath: Scalars['String']['input'];
  params: Event_SectionsMutation;
};

export type DocumentUpdateMutation = {
  pages?: InputMaybe<PagesMutation>;
  globals?: InputMaybe<GlobalsMutation>;
  events?: InputMaybe<EventsMutation>;
  event_sections?: InputMaybe<Event_SectionsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  pages?: InputMaybe<PagesMutation>;
  globals?: InputMaybe<GlobalsMutation>;
  events?: InputMaybe<EventsMutation>;
  event_sections?: InputMaybe<Event_SectionsMutation>;
};

export type PagesHomeStatsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type PagesHomeClientsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
};

export type PagesHomeMutation = {
  heroEyebrow?: InputMaybe<Scalars['String']['input']>;
  heroTitle1?: InputMaybe<Scalars['String']['input']>;
  heroTitleHighlight?: InputMaybe<Scalars['String']['input']>;
  heroTitle2?: InputMaybe<Scalars['String']['input']>;
  heroDescription?: InputMaybe<Scalars['String']['input']>;
  heroPrimaryButton?: InputMaybe<Scalars['String']['input']>;
  heroSecondaryButton?: InputMaybe<Scalars['String']['input']>;
  stats?: InputMaybe<Array<InputMaybe<PagesHomeStatsMutation>>>;
  clienteleEyebrow?: InputMaybe<Scalars['String']['input']>;
  clienteleTitle?: InputMaybe<Scalars['String']['input']>;
  clients?: InputMaybe<Array<InputMaybe<PagesHomeClientsMutation>>>;
};

export type PagesAboutMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title1?: InputMaybe<Scalars['String']['input']>;
  titleHighlight?: InputMaybe<Scalars['String']['input']>;
  title2?: InputMaybe<Scalars['String']['input']>;
  paragraph1?: InputMaybe<Scalars['String']['input']>;
  paragraph2?: InputMaybe<Scalars['String']['input']>;
  paragraph3?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type PagesContactContactCardsMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  lines?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PagesContactStatsMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type PagesContactMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  titleHighlight?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  mapUrl?: InputMaybe<Scalars['String']['input']>;
  contactCards?: InputMaybe<Array<InputMaybe<PagesContactContactCardsMutation>>>;
  footerText1?: InputMaybe<Scalars['String']['input']>;
  footerText2?: InputMaybe<Scalars['String']['input']>;
  stats?: InputMaybe<Array<InputMaybe<PagesContactStatsMutation>>>;
};

export type PagesGalleryImagesMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  thumb?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type PagesGalleryMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  images?: InputMaybe<Array<InputMaybe<PagesGalleryImagesMutation>>>;
};

export type PagesModelsModelsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type PagesModelsMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  ctaText?: InputMaybe<Scalars['String']['input']>;
  ctaLink?: InputMaybe<Scalars['String']['input']>;
  models?: InputMaybe<Array<InputMaybe<PagesModelsModelsMutation>>>;
};

export type PagesMutation = {
  home?: InputMaybe<PagesHomeMutation>;
  about?: InputMaybe<PagesAboutMutation>;
  contact?: InputMaybe<PagesContactMutation>;
  gallery?: InputMaybe<PagesGalleryMutation>;
  models?: InputMaybe<PagesModelsMutation>;
};

export type GlobalsNavbarNavLinksMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  path?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalsNavbarSocialLinksMutation = {
  platform?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalsNavbarMutation = {
  navLinks?: InputMaybe<Array<InputMaybe<GlobalsNavbarNavLinksMutation>>>;
  socialLinks?: InputMaybe<Array<InputMaybe<GlobalsNavbarSocialLinksMutation>>>;
  ctaText?: InputMaybe<Scalars['String']['input']>;
  ctaLink?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalsFooterQuickLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalsFooterLegalLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalsFooterMutation = {
  description?: InputMaybe<Scalars['String']['input']>;
  quickLinks?: InputMaybe<Array<InputMaybe<GlobalsFooterQuickLinksMutation>>>;
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  copyright?: InputMaybe<Scalars['String']['input']>;
  legalLinks?: InputMaybe<Array<InputMaybe<GlobalsFooterLegalLinksMutation>>>;
};

export type GlobalsMutation = {
  navbar?: InputMaybe<GlobalsNavbarMutation>;
  footer?: InputMaybe<GlobalsFooterMutation>;
};

export type EventsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  images?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type Event_SectionsMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  start?: InputMaybe<Scalars['String']['input']>;
  end?: InputMaybe<Scalars['String']['input']>;
  footer?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type PagesHomeStatsFilter = {
  value?: StringFilter | null | undefined;
  label?: StringFilter | null | undefined;
  icon?: StringFilter | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type PagesHomeClientsFilter = {
  name?: StringFilter | null | undefined;
  logo?: ImageFilter | null | undefined;
};

export type PagesHomeFilter = {
  heroEyebrow?: StringFilter | null | undefined;
  heroTitle1?: StringFilter | null | undefined;
  heroTitleHighlight?: StringFilter | null | undefined;
  heroTitle2?: StringFilter | null | undefined;
  heroDescription?: StringFilter | null | undefined;
  heroPrimaryButton?: StringFilter | null | undefined;
  heroSecondaryButton?: StringFilter | null | undefined;
  stats?: PagesHomeStatsFilter | null | undefined;
  clienteleEyebrow?: StringFilter | null | undefined;
  clienteleTitle?: StringFilter | null | undefined;
  clients?: PagesHomeClientsFilter | null | undefined;
};

export type PagesAboutFilter = {
  eyebrow?: StringFilter | null | undefined;
  title1?: StringFilter | null | undefined;
  titleHighlight?: StringFilter | null | undefined;
  title2?: StringFilter | null | undefined;
  paragraph1?: StringFilter | null | undefined;
  paragraph2?: StringFilter | null | undefined;
  paragraph3?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
};

export type PagesContactContactCardsFilter = {
  icon?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  lines?: StringFilter | null | undefined;
};

export type PagesContactStatsFilter = {
  icon?: StringFilter | null | undefined;
  value?: StringFilter | null | undefined;
  label?: StringFilter | null | undefined;
};

export type PagesContactFilter = {
  eyebrow?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  titleHighlight?: StringFilter | null | undefined;
  subtitle?: StringFilter | null | undefined;
  mapUrl?: StringFilter | null | undefined;
  contactCards?: PagesContactContactCardsFilter | null | undefined;
  footerText1?: StringFilter | null | undefined;
  footerText2?: StringFilter | null | undefined;
  stats?: PagesContactStatsFilter | null | undefined;
};

export type PagesGalleryImagesFilter = {
  image?: ImageFilter | null | undefined;
  thumb?: ImageFilter | null | undefined;
  alt?: StringFilter | null | undefined;
};

export type PagesGalleryFilter = {
  eyebrow?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  images?: PagesGalleryImagesFilter | null | undefined;
};

export type PagesModelsModelsFilter = {
  name?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
};

export type PagesModelsFilter = {
  eyebrow?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  ctaText?: StringFilter | null | undefined;
  ctaLink?: StringFilter | null | undefined;
  models?: PagesModelsModelsFilter | null | undefined;
};

export type PagesFilter = {
  home?: PagesHomeFilter | null | undefined;
  about?: PagesAboutFilter | null | undefined;
  contact?: PagesContactFilter | null | undefined;
  gallery?: PagesGalleryFilter | null | undefined;
  models?: PagesModelsFilter | null | undefined;
};

export type GlobalsNavbarNavLinksFilter = {
  name?: StringFilter | null | undefined;
  path?: StringFilter | null | undefined;
};

export type GlobalsNavbarSocialLinksFilter = {
  platform?: StringFilter | null | undefined;
  url?: StringFilter | null | undefined;
};

export type GlobalsNavbarFilter = {
  navLinks?: GlobalsNavbarNavLinksFilter | null | undefined;
  socialLinks?: GlobalsNavbarSocialLinksFilter | null | undefined;
  ctaText?: StringFilter | null | undefined;
  ctaLink?: StringFilter | null | undefined;
};

export type GlobalsFooterQuickLinksFilter = {
  label?: StringFilter | null | undefined;
  url?: StringFilter | null | undefined;
};

export type GlobalsFooterLegalLinksFilter = {
  label?: StringFilter | null | undefined;
  url?: StringFilter | null | undefined;
};

export type GlobalsFooterFilter = {
  description?: StringFilter | null | undefined;
  quickLinks?: GlobalsFooterQuickLinksFilter | null | undefined;
  email?: StringFilter | null | undefined;
  phone?: StringFilter | null | undefined;
  location?: StringFilter | null | undefined;
  copyright?: StringFilter | null | undefined;
  legalLinks?: GlobalsFooterLegalLinksFilter | null | undefined;
};

export type GlobalsFilter = {
  navbar?: GlobalsNavbarFilter | null | undefined;
  footer?: GlobalsFooterFilter | null | undefined;
};

export type EventsFilter = {
  title?: StringFilter | null | undefined;
  subtitle?: StringFilter | null | undefined;
  images?: ImageFilter | null | undefined;
};

export type Event_SectionsFilter = {
  eyebrow?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  start?: StringFilter | null | undefined;
  end?: StringFilter | null | undefined;
  footer?: StringFilter | null | undefined;
  items?: StringFilter | null | undefined;
};

type PagesParts_PagesHome_Fragment = { __typename: 'PagesHome', heroEyebrow: string | null, heroTitle1: string | null, heroTitleHighlight: string | null, heroTitle2: string | null, heroDescription: string | null, heroPrimaryButton: string | null, heroSecondaryButton: string | null, clienteleEyebrow: string | null, clienteleTitle: string | null, stats: Array<{ __typename: 'PagesHomeStats', value: string | null, label: string | null, icon: string | null } | null> | null, clients: Array<{ __typename: 'PagesHomeClients', name: string | null, logo: string | null } | null> | null };

type PagesParts_PagesAbout_Fragment = { __typename: 'PagesAbout', eyebrow: string | null, title1: string | null, titleHighlight: string | null, title2: string | null, paragraph1: string | null, paragraph2: string | null, paragraph3: string | null, image: string | null };

type PagesParts_PagesContact_Fragment = { __typename: 'PagesContact', eyebrow: string | null, title: string | null, titleHighlight: string | null, subtitle: string | null, mapUrl: string | null, footerText1: string | null, footerText2: string | null, contactCards: Array<{ __typename: 'PagesContactContactCards', icon: string | null, title: string | null, lines: Array<string | null> | null } | null> | null, stats: Array<{ __typename: 'PagesContactStats', icon: string | null, value: string | null, label: string | null } | null> | null };

type PagesParts_PagesGallery_Fragment = { __typename: 'PagesGallery', eyebrow: string | null, title: string | null, images: Array<{ __typename: 'PagesGalleryImages', image: string | null, thumb: string | null, alt: string | null } | null> | null };

type PagesParts_PagesModels_Fragment = { __typename: 'PagesModels', eyebrow: string | null, title: string | null, description: string | null, ctaText: string | null, ctaLink: string | null, models: Array<{ __typename: 'PagesModelsModels', name: string | null, title: string | null, image: string | null } | null> | null };

export type PagesPartsFragment =
  | PagesParts_PagesHome_Fragment
  | PagesParts_PagesAbout_Fragment
  | PagesParts_PagesContact_Fragment
  | PagesParts_PagesGallery_Fragment
  | PagesParts_PagesModels_Fragment
;

type GlobalsParts_GlobalsNavbar_Fragment = { __typename: 'GlobalsNavbar', ctaText: string | null, ctaLink: string | null, navLinks: Array<{ __typename: 'GlobalsNavbarNavLinks', name: string | null, path: string | null } | null> | null, socialLinks: Array<{ __typename: 'GlobalsNavbarSocialLinks', platform: string | null, url: string | null } | null> | null };

type GlobalsParts_GlobalsFooter_Fragment = { __typename: 'GlobalsFooter', description: string | null, email: string | null, phone: string | null, location: string | null, copyright: string | null, quickLinks: Array<{ __typename: 'GlobalsFooterQuickLinks', label: string | null, url: string | null } | null> | null, legalLinks: Array<{ __typename: 'GlobalsFooterLegalLinks', label: string | null, url: string | null } | null> | null };

export type GlobalsPartsFragment =
  | GlobalsParts_GlobalsNavbar_Fragment
  | GlobalsParts_GlobalsFooter_Fragment
;

export type EventsPartsFragment = { __typename: 'Events', title: string, subtitle: string | null, images: Array<string | null> | null };

export type Event_SectionsPartsFragment = { __typename: 'Event_sections', eyebrow: string | null, title: string, description: string | null, start: string | null, end: string | null, footer: string | null, items: Array<string | null> | null };

export type PagesQueryVariables = Exact<{
  relativePath: string;
}>;


export type PagesQuery = { pages:
    | { __typename: 'PagesHome', id: string, heroEyebrow: string | null, heroTitle1: string | null, heroTitleHighlight: string | null, heroTitle2: string | null, heroDescription: string | null, heroPrimaryButton: string | null, heroSecondaryButton: string | null, clienteleEyebrow: string | null, clienteleTitle: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stats: Array<{ __typename: 'PagesHomeStats', value: string | null, label: string | null, icon: string | null } | null> | null, clients: Array<{ __typename: 'PagesHomeClients', name: string | null, logo: string | null } | null> | null }
    | { __typename: 'PagesAbout', id: string, eyebrow: string | null, title1: string | null, titleHighlight: string | null, title2: string | null, paragraph1: string | null, paragraph2: string | null, paragraph3: string | null, image: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } }
    | { __typename: 'PagesContact', id: string, eyebrow: string | null, title: string | null, titleHighlight: string | null, subtitle: string | null, mapUrl: string | null, footerText1: string | null, footerText2: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, contactCards: Array<{ __typename: 'PagesContactContactCards', icon: string | null, title: string | null, lines: Array<string | null> | null } | null> | null, stats: Array<{ __typename: 'PagesContactStats', icon: string | null, value: string | null, label: string | null } | null> | null }
    | { __typename: 'PagesGallery', id: string, eyebrow: string | null, title: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, images: Array<{ __typename: 'PagesGalleryImages', image: string | null, thumb: string | null, alt: string | null } | null> | null }
    | { __typename: 'PagesModels', id: string, eyebrow: string | null, title: string | null, description: string | null, ctaText: string | null, ctaLink: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, models: Array<{ __typename: 'PagesModelsModels', name: string | null, title: string | null, image: string | null } | null> | null }
   };

export type PagesConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: PagesFilter | null | undefined;
}>;


export type PagesConnectionQuery = { pagesConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node:
        | { __typename: 'PagesHome', id: string, heroEyebrow: string | null, heroTitle1: string | null, heroTitleHighlight: string | null, heroTitle2: string | null, heroDescription: string | null, heroPrimaryButton: string | null, heroSecondaryButton: string | null, clienteleEyebrow: string | null, clienteleTitle: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stats: Array<{ __typename: 'PagesHomeStats', value: string | null, label: string | null, icon: string | null } | null> | null, clients: Array<{ __typename: 'PagesHomeClients', name: string | null, logo: string | null } | null> | null }
        | { __typename: 'PagesAbout', id: string, eyebrow: string | null, title1: string | null, titleHighlight: string | null, title2: string | null, paragraph1: string | null, paragraph2: string | null, paragraph3: string | null, image: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } }
        | { __typename: 'PagesContact', id: string, eyebrow: string | null, title: string | null, titleHighlight: string | null, subtitle: string | null, mapUrl: string | null, footerText1: string | null, footerText2: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, contactCards: Array<{ __typename: 'PagesContactContactCards', icon: string | null, title: string | null, lines: Array<string | null> | null } | null> | null, stats: Array<{ __typename: 'PagesContactStats', icon: string | null, value: string | null, label: string | null } | null> | null }
        | { __typename: 'PagesGallery', id: string, eyebrow: string | null, title: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, images: Array<{ __typename: 'PagesGalleryImages', image: string | null, thumb: string | null, alt: string | null } | null> | null }
        | { __typename: 'PagesModels', id: string, eyebrow: string | null, title: string | null, description: string | null, ctaText: string | null, ctaLink: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, models: Array<{ __typename: 'PagesModelsModels', name: string | null, title: string | null, image: string | null } | null> | null }
       | null } | null> | null } };

export type GlobalsQueryVariables = Exact<{
  relativePath: string;
}>;


export type GlobalsQuery = { globals:
    | { __typename: 'GlobalsNavbar', id: string, ctaText: string | null, ctaLink: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, navLinks: Array<{ __typename: 'GlobalsNavbarNavLinks', name: string | null, path: string | null } | null> | null, socialLinks: Array<{ __typename: 'GlobalsNavbarSocialLinks', platform: string | null, url: string | null } | null> | null }
    | { __typename: 'GlobalsFooter', id: string, description: string | null, email: string | null, phone: string | null, location: string | null, copyright: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, quickLinks: Array<{ __typename: 'GlobalsFooterQuickLinks', label: string | null, url: string | null } | null> | null, legalLinks: Array<{ __typename: 'GlobalsFooterLegalLinks', label: string | null, url: string | null } | null> | null }
   };

export type GlobalsConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: GlobalsFilter | null | undefined;
}>;


export type GlobalsConnectionQuery = { globalsConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node:
        | { __typename: 'GlobalsNavbar', id: string, ctaText: string | null, ctaLink: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, navLinks: Array<{ __typename: 'GlobalsNavbarNavLinks', name: string | null, path: string | null } | null> | null, socialLinks: Array<{ __typename: 'GlobalsNavbarSocialLinks', platform: string | null, url: string | null } | null> | null }
        | { __typename: 'GlobalsFooter', id: string, description: string | null, email: string | null, phone: string | null, location: string | null, copyright: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, quickLinks: Array<{ __typename: 'GlobalsFooterQuickLinks', label: string | null, url: string | null } | null> | null, legalLinks: Array<{ __typename: 'GlobalsFooterLegalLinks', label: string | null, url: string | null } | null> | null }
       | null } | null> | null } };

export type EventsQueryVariables = Exact<{
  relativePath: string;
}>;


export type EventsQuery = { events: { __typename: 'Events', id: string, title: string, subtitle: string | null, images: Array<string | null> | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type EventsConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: EventsFilter | null | undefined;
}>;


export type EventsConnectionQuery = { eventsConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Events', id: string, title: string, subtitle: string | null, images: Array<string | null> | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Event_SectionsQueryVariables = Exact<{
  relativePath: string;
}>;


export type Event_SectionsQuery = { event_sections: { __typename: 'Event_sections', id: string, eyebrow: string | null, title: string, description: string | null, start: string | null, end: string | null, footer: string | null, items: Array<string | null> | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Event_SectionsConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: Event_SectionsFilter | null | undefined;
}>;


export type Event_SectionsConnectionQuery = { event_sectionsConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Event_sections', id: string, eyebrow: string | null, title: string, description: string | null, start: string | null, end: string | null, footer: string | null, items: Array<string | null> | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const PagesPartsFragmentDoc = gql`
    fragment PagesParts on Pages {
  __typename
  ... on PagesHome {
    heroEyebrow
    heroTitle1
    heroTitleHighlight
    heroTitle2
    heroDescription
    heroPrimaryButton
    heroSecondaryButton
    stats {
      __typename
      value
      label
      icon
    }
    clienteleEyebrow
    clienteleTitle
    clients {
      __typename
      name
      logo
    }
  }
  ... on PagesAbout {
    eyebrow
    title1
    titleHighlight
    title2
    paragraph1
    paragraph2
    paragraph3
    image
  }
  ... on PagesContact {
    eyebrow
    title
    titleHighlight
    subtitle
    mapUrl
    contactCards {
      __typename
      icon
      title
      lines
    }
    footerText1
    footerText2
    stats {
      __typename
      icon
      value
      label
    }
  }
  ... on PagesGallery {
    eyebrow
    title
    images {
      __typename
      image
      thumb
      alt
    }
  }
  ... on PagesModels {
    eyebrow
    title
    description
    ctaText
    ctaLink
    models {
      __typename
      name
      title
      image
    }
  }
}
    `;
export const GlobalsPartsFragmentDoc = gql`
    fragment GlobalsParts on Globals {
  __typename
  ... on GlobalsNavbar {
    navLinks {
      __typename
      name
      path
    }
    socialLinks {
      __typename
      platform
      url
    }
    ctaText
    ctaLink
  }
  ... on GlobalsFooter {
    description
    quickLinks {
      __typename
      label
      url
    }
    email
    phone
    location
    copyright
    legalLinks {
      __typename
      label
      url
    }
  }
}
    `;
export const EventsPartsFragmentDoc = gql`
    fragment EventsParts on Events {
  __typename
  title
  subtitle
  images
}
    `;
export const Event_SectionsPartsFragmentDoc = gql`
    fragment Event_sectionsParts on Event_sections {
  __typename
  eyebrow
  title
  description
  start
  end
  footer
  items
}
    `;
export const PagesDocument = gql`
    query pages($relativePath: String!) {
  pages(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PagesParts
  }
}
    ${PagesPartsFragmentDoc}`;
export const PagesConnectionDocument = gql`
    query pagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PagesFilter) {
  pagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PagesParts
      }
    }
  }
}
    ${PagesPartsFragmentDoc}`;
export const GlobalsDocument = gql`
    query globals($relativePath: String!) {
  globals(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GlobalsParts
  }
}
    ${GlobalsPartsFragmentDoc}`;
export const GlobalsConnectionDocument = gql`
    query globalsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GlobalsFilter) {
  globalsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GlobalsParts
      }
    }
  }
}
    ${GlobalsPartsFragmentDoc}`;
export const EventsDocument = gql`
    query events($relativePath: String!) {
  events(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EventsParts
  }
}
    ${EventsPartsFragmentDoc}`;
export const EventsConnectionDocument = gql`
    query eventsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EventsFilter) {
  eventsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EventsParts
      }
    }
  }
}
    ${EventsPartsFragmentDoc}`;
export const Event_SectionsDocument = gql`
    query event_sections($relativePath: String!) {
  event_sections(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Event_sectionsParts
  }
}
    ${Event_SectionsPartsFragmentDoc}`;
export const Event_SectionsConnectionDocument = gql`
    query event_sectionsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Event_sectionsFilter) {
  event_sectionsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Event_sectionsParts
      }
    }
  }
}
    ${Event_SectionsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      pages(variables: PagesQueryVariables, options?: C): Promise<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}> {
        return requester<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}, PagesQueryVariables>(PagesDocument, variables, options);
      },
    pagesConnection(variables?: PagesConnectionQueryVariables, options?: C): Promise<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}> {
        return requester<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}, PagesConnectionQueryVariables>(PagesConnectionDocument, variables, options);
      },
    globals(variables: GlobalsQueryVariables, options?: C): Promise<{data: GlobalsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalsQueryVariables, query: string}> {
        return requester<{data: GlobalsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalsQueryVariables, query: string}, GlobalsQueryVariables>(GlobalsDocument, variables, options);
      },
    globalsConnection(variables?: GlobalsConnectionQueryVariables, options?: C): Promise<{data: GlobalsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalsConnectionQueryVariables, query: string}> {
        return requester<{data: GlobalsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalsConnectionQueryVariables, query: string}, GlobalsConnectionQueryVariables>(GlobalsConnectionDocument, variables, options);
      },
    events(variables: EventsQueryVariables, options?: C): Promise<{data: EventsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsQueryVariables, query: string}> {
        return requester<{data: EventsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsQueryVariables, query: string}, EventsQueryVariables>(EventsDocument, variables, options);
      },
    eventsConnection(variables?: EventsConnectionQueryVariables, options?: C): Promise<{data: EventsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsConnectionQueryVariables, query: string}> {
        return requester<{data: EventsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsConnectionQueryVariables, query: string}, EventsConnectionQueryVariables>(EventsConnectionDocument, variables, options);
      },
    event_sections(variables: Event_SectionsQueryVariables, options?: C): Promise<{data: Event_SectionsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Event_SectionsQueryVariables, query: string}> {
        return requester<{data: Event_SectionsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Event_SectionsQueryVariables, query: string}, Event_SectionsQueryVariables>(Event_SectionsDocument, variables, options);
      },
    event_sectionsConnection(variables?: Event_SectionsConnectionQueryVariables, options?: C): Promise<{data: Event_SectionsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Event_SectionsConnectionQueryVariables, query: string}> {
        return requester<{data: Event_SectionsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Event_SectionsConnectionQueryVariables, query: string}, Event_SectionsConnectionQueryVariables>(Event_SectionsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  