//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  /** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  home: Home;
  homeConnection: HomeConnection;
  about: About;
  aboutConnection: AboutConnection;
  contact: Contact;
  contactConnection: ContactConnection;
  gallery: Gallery;
  galleryConnection: GalleryConnection;
  models: Models;
  modelsConnection: ModelsConnection;
  navbar: Navbar;
  navbarConnection: NavbarConnection;
  footer: Footer;
  footerConnection: FooterConnection;
  events: Events;
  eventsConnection: EventsConnection;
  event_sections: Event_Sections;
  event_sectionsConnection: Event_SectionsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QueryAboutArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
};


export type QueryContactArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
};


export type QueryGalleryArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGalleryConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GalleryFilter>;
};


export type QueryModelsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryModelsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ModelsFilter>;
};


export type QueryNavbarArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNavbarConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NavbarFilter>;
};


export type QueryFooterArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFooterConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FooterFilter>;
};


export type QueryEventsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventsFilter>;
};


export type QueryEvent_SectionsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEvent_SectionsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Event_SectionsFilter>;
};

export type DocumentFilter = {
  home?: InputMaybe<HomeFilter>;
  about?: InputMaybe<AboutFilter>;
  contact?: InputMaybe<ContactFilter>;
  gallery?: InputMaybe<GalleryFilter>;
  models?: InputMaybe<ModelsFilter>;
  navbar?: InputMaybe<NavbarFilter>;
  footer?: InputMaybe<FooterFilter>;
  events?: InputMaybe<EventsFilter>;
  event_sections?: InputMaybe<Event_SectionsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Home | About | Contact | Gallery | Models | Navbar | Footer | Events | Event_Sections | Folder;

export type HomeStats = {
  __typename?: 'HomeStats';
  value?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
};

export type HomeClients = {
  __typename?: 'HomeClients';
  name?: Maybe<Scalars['String']['output']>;
  logo?: Maybe<Scalars['String']['output']>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  heroEyebrow?: Maybe<Scalars['String']['output']>;
  heroTitle1?: Maybe<Scalars['String']['output']>;
  heroTitleHighlight?: Maybe<Scalars['String']['output']>;
  heroTitle2?: Maybe<Scalars['String']['output']>;
  heroDescription?: Maybe<Scalars['String']['output']>;
  heroPrimaryButton?: Maybe<Scalars['String']['output']>;
  heroSecondaryButton?: Maybe<Scalars['String']['output']>;
  stats?: Maybe<Array<Maybe<HomeStats>>>;
  clienteleEyebrow?: Maybe<Scalars['String']['output']>;
  clienteleTitle?: Maybe<Scalars['String']['output']>;
  clients?: Maybe<Array<Maybe<HomeClients>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeStatsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeClientsFilter = {
  name?: InputMaybe<StringFilter>;
  logo?: InputMaybe<ImageFilter>;
};

export type HomeFilter = {
  heroEyebrow?: InputMaybe<StringFilter>;
  heroTitle1?: InputMaybe<StringFilter>;
  heroTitleHighlight?: InputMaybe<StringFilter>;
  heroTitle2?: InputMaybe<StringFilter>;
  heroDescription?: InputMaybe<StringFilter>;
  heroPrimaryButton?: InputMaybe<StringFilter>;
  heroSecondaryButton?: InputMaybe<StringFilter>;
  stats?: InputMaybe<HomeStatsFilter>;
  clienteleEyebrow?: InputMaybe<StringFilter>;
  clienteleTitle?: InputMaybe<StringFilter>;
  clients?: InputMaybe<HomeClientsFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type About = Node & Document & {
  __typename?: 'About';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title1?: Maybe<Scalars['String']['output']>;
  titleHighlight?: Maybe<Scalars['String']['output']>;
  title2?: Maybe<Scalars['String']['output']>;
  paragraph1?: Maybe<Scalars['String']['output']>;
  paragraph2?: Maybe<Scalars['String']['output']>;
  paragraph3?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AboutFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title1?: InputMaybe<StringFilter>;
  titleHighlight?: InputMaybe<StringFilter>;
  title2?: InputMaybe<StringFilter>;
  paragraph1?: InputMaybe<StringFilter>;
  paragraph2?: InputMaybe<StringFilter>;
  paragraph3?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type AboutConnectionEdges = {
  __typename?: 'AboutConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<About>;
};

export type AboutConnection = Connection & {
  __typename?: 'AboutConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutConnectionEdges>>>;
};

export type ContactContactCards = {
  __typename?: 'ContactContactCards';
  icon?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  lines?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type ContactStats = {
  __typename?: 'ContactStats';
  icon?: Maybe<Scalars['String']['output']>;
  value?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type Contact = Node & Document & {
  __typename?: 'Contact';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  titleHighlight?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  mapUrl?: Maybe<Scalars['String']['output']>;
  contactCards?: Maybe<Array<Maybe<ContactContactCards>>>;
  footerText1?: Maybe<Scalars['String']['output']>;
  footerText2?: Maybe<Scalars['String']['output']>;
  stats?: Maybe<Array<Maybe<ContactStats>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactContactCardsFilter = {
  icon?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  lines?: InputMaybe<StringFilter>;
};

export type ContactStatsFilter = {
  icon?: InputMaybe<StringFilter>;
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type ContactFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  titleHighlight?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  mapUrl?: InputMaybe<StringFilter>;
  contactCards?: InputMaybe<ContactContactCardsFilter>;
  footerText1?: InputMaybe<StringFilter>;
  footerText2?: InputMaybe<StringFilter>;
  stats?: InputMaybe<ContactStatsFilter>;
};

export type ContactConnectionEdges = {
  __typename?: 'ContactConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contact>;
};

export type ContactConnection = Connection & {
  __typename?: 'ContactConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactConnectionEdges>>>;
};

export type GalleryImages = {
  __typename?: 'GalleryImages';
  image?: Maybe<Scalars['String']['output']>;
  thumb?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type Gallery = Node & Document & {
  __typename?: 'Gallery';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  images?: Maybe<Array<Maybe<GalleryImages>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GalleryImagesFilter = {
  image?: InputMaybe<ImageFilter>;
  thumb?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type GalleryFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  images?: InputMaybe<GalleryImagesFilter>;
};

export type GalleryConnectionEdges = {
  __typename?: 'GalleryConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Gallery>;
};

export type GalleryConnection = Connection & {
  __typename?: 'GalleryConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GalleryConnectionEdges>>>;
};

export type ModelsModels = {
  __typename?: 'ModelsModels';
  name?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type Models = Node & Document & {
  __typename?: 'Models';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  ctaText?: Maybe<Scalars['String']['output']>;
  ctaLink?: Maybe<Scalars['String']['output']>;
  models?: Maybe<Array<Maybe<ModelsModels>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ModelsModelsFilter = {
  name?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type ModelsFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  ctaText?: InputMaybe<StringFilter>;
  ctaLink?: InputMaybe<StringFilter>;
  models?: InputMaybe<ModelsModelsFilter>;
};

export type ModelsConnectionEdges = {
  __typename?: 'ModelsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Models>;
};

export type ModelsConnection = Connection & {
  __typename?: 'ModelsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ModelsConnectionEdges>>>;
};

export type NavbarNavLinks = {
  __typename?: 'NavbarNavLinks';
  name?: Maybe<Scalars['String']['output']>;
  path?: Maybe<Scalars['String']['output']>;
};

export type NavbarSocialLinks = {
  __typename?: 'NavbarSocialLinks';
  platform?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type Navbar = Node & Document & {
  __typename?: 'Navbar';
  navLinks?: Maybe<Array<Maybe<NavbarNavLinks>>>;
  socialLinks?: Maybe<Array<Maybe<NavbarSocialLinks>>>;
  ctaText?: Maybe<Scalars['String']['output']>;
  ctaLink?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NavbarNavLinksFilter = {
  name?: InputMaybe<StringFilter>;
  path?: InputMaybe<StringFilter>;
};

export type NavbarSocialLinksFilter = {
  platform?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type NavbarFilter = {
  navLinks?: InputMaybe<NavbarNavLinksFilter>;
  socialLinks?: InputMaybe<NavbarSocialLinksFilter>;
  ctaText?: InputMaybe<StringFilter>;
  ctaLink?: InputMaybe<StringFilter>;
};

export type NavbarConnectionEdges = {
  __typename?: 'NavbarConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Navbar>;
};

export type NavbarConnection = Connection & {
  __typename?: 'NavbarConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NavbarConnectionEdges>>>;
};

export type FooterQuickLinks = {
  __typename?: 'FooterQuickLinks';
  label?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type FooterLegalLinks = {
  __typename?: 'FooterLegalLinks';
  label?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type Footer = Node & Document & {
  __typename?: 'Footer';
  description?: Maybe<Scalars['String']['output']>;
  quickLinks?: Maybe<Array<Maybe<FooterQuickLinks>>>;
  email?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  copyright?: Maybe<Scalars['String']['output']>;
  legalLinks?: Maybe<Array<Maybe<FooterLegalLinks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FooterQuickLinksFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type FooterLegalLinksFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type FooterFilter = {
  description?: InputMaybe<StringFilter>;
  quickLinks?: InputMaybe<FooterQuickLinksFilter>;
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  copyright?: InputMaybe<StringFilter>;
  legalLinks?: InputMaybe<FooterLegalLinksFilter>;
};

export type FooterConnectionEdges = {
  __typename?: 'FooterConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Footer>;
};

export type FooterConnection = Connection & {
  __typename?: 'FooterConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FooterConnectionEdges>>>;
};

export type Events = Node & Document & {
  __typename?: 'Events';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  images?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type EventsFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  images?: InputMaybe<ImageFilter>;
};

export type EventsConnectionEdges = {
  __typename?: 'EventsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Events>;
};

export type EventsConnection = Connection & {
  __typename?: 'EventsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EventsConnectionEdges>>>;
};

export type Event_Sections = Node & Document & {
  __typename?: 'Event_sections';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  start?: Maybe<Scalars['String']['output']>;
  end?: Maybe<Scalars['String']['output']>;
  footer?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Event_SectionsFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  start?: InputMaybe<StringFilter>;
  end?: InputMaybe<StringFilter>;
  footer?: InputMaybe<StringFilter>;
  items?: InputMaybe<StringFilter>;
};

export type Event_SectionsConnectionEdges = {
  __typename?: 'Event_sectionsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Event_Sections>;
};

export type Event_SectionsConnection = Connection & {
  __typename?: 'Event_sectionsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Event_SectionsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHome: Home;
  createHome: Home;
  updateAbout: About;
  createAbout: About;
  updateContact: Contact;
  createContact: Contact;
  updateGallery: Gallery;
  createGallery: Gallery;
  updateModels: Models;
  createModels: Models;
  updateNavbar: Navbar;
  createNavbar: Navbar;
  updateFooter: Footer;
  createFooter: Footer;
  updateEvents: Events;
  createEvents: Events;
  updateEvent_sections: Event_Sections;
  createEvent_sections: Event_Sections;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationCreateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationUpdateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationCreateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationUpdateGalleryArgs = {
  relativePath: Scalars['String']['input'];
  params: GalleryMutation;
};


export type MutationCreateGalleryArgs = {
  relativePath: Scalars['String']['input'];
  params: GalleryMutation;
};


export type MutationUpdateModelsArgs = {
  relativePath: Scalars['String']['input'];
  params: ModelsMutation;
};


export type MutationCreateModelsArgs = {
  relativePath: Scalars['String']['input'];
  params: ModelsMutation;
};


export type MutationUpdateNavbarArgs = {
  relativePath: Scalars['String']['input'];
  params: NavbarMutation;
};


export type MutationCreateNavbarArgs = {
  relativePath: Scalars['String']['input'];
  params: NavbarMutation;
};


export type MutationUpdateFooterArgs = {
  relativePath: Scalars['String']['input'];
  params: FooterMutation;
};


export type MutationCreateFooterArgs = {
  relativePath: Scalars['String']['input'];
  params: FooterMutation;
};


export type MutationUpdateEventsArgs = {
  relativePath: Scalars['String']['input'];
  params: EventsMutation;
};


export type MutationCreateEventsArgs = {
  relativePath: Scalars['String']['input'];
  params: EventsMutation;
};


export type MutationUpdateEvent_SectionsArgs = {
  relativePath: Scalars['String']['input'];
  params: Event_SectionsMutation;
};


export type MutationCreateEvent_SectionsArgs = {
  relativePath: Scalars['String']['input'];
  params: Event_SectionsMutation;
};

export type DocumentUpdateMutation = {
  home?: InputMaybe<HomeMutation>;
  about?: InputMaybe<AboutMutation>;
  contact?: InputMaybe<ContactMutation>;
  gallery?: InputMaybe<GalleryMutation>;
  models?: InputMaybe<ModelsMutation>;
  navbar?: InputMaybe<NavbarMutation>;
  footer?: InputMaybe<FooterMutation>;
  events?: InputMaybe<EventsMutation>;
  event_sections?: InputMaybe<Event_SectionsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  home?: InputMaybe<HomeMutation>;
  about?: InputMaybe<AboutMutation>;
  contact?: InputMaybe<ContactMutation>;
  gallery?: InputMaybe<GalleryMutation>;
  models?: InputMaybe<ModelsMutation>;
  navbar?: InputMaybe<NavbarMutation>;
  footer?: InputMaybe<FooterMutation>;
  events?: InputMaybe<EventsMutation>;
  event_sections?: InputMaybe<Event_SectionsMutation>;
};

export type HomeStatsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type HomeClientsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  heroEyebrow?: InputMaybe<Scalars['String']['input']>;
  heroTitle1?: InputMaybe<Scalars['String']['input']>;
  heroTitleHighlight?: InputMaybe<Scalars['String']['input']>;
  heroTitle2?: InputMaybe<Scalars['String']['input']>;
  heroDescription?: InputMaybe<Scalars['String']['input']>;
  heroPrimaryButton?: InputMaybe<Scalars['String']['input']>;
  heroSecondaryButton?: InputMaybe<Scalars['String']['input']>;
  stats?: InputMaybe<Array<InputMaybe<HomeStatsMutation>>>;
  clienteleEyebrow?: InputMaybe<Scalars['String']['input']>;
  clienteleTitle?: InputMaybe<Scalars['String']['input']>;
  clients?: InputMaybe<Array<InputMaybe<HomeClientsMutation>>>;
};

export type AboutMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title1?: InputMaybe<Scalars['String']['input']>;
  titleHighlight?: InputMaybe<Scalars['String']['input']>;
  title2?: InputMaybe<Scalars['String']['input']>;
  paragraph1?: InputMaybe<Scalars['String']['input']>;
  paragraph2?: InputMaybe<Scalars['String']['input']>;
  paragraph3?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type ContactContactCardsMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  lines?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ContactStatsMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type ContactMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  titleHighlight?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  mapUrl?: InputMaybe<Scalars['String']['input']>;
  contactCards?: InputMaybe<Array<InputMaybe<ContactContactCardsMutation>>>;
  footerText1?: InputMaybe<Scalars['String']['input']>;
  footerText2?: InputMaybe<Scalars['String']['input']>;
  stats?: InputMaybe<Array<InputMaybe<ContactStatsMutation>>>;
};

export type GalleryImagesMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  thumb?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type GalleryMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  images?: InputMaybe<Array<InputMaybe<GalleryImagesMutation>>>;
};

export type ModelsModelsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type ModelsMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  ctaText?: InputMaybe<Scalars['String']['input']>;
  ctaLink?: InputMaybe<Scalars['String']['input']>;
  models?: InputMaybe<Array<InputMaybe<ModelsModelsMutation>>>;
};

export type NavbarNavLinksMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  path?: InputMaybe<Scalars['String']['input']>;
};

export type NavbarSocialLinksMutation = {
  platform?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type NavbarMutation = {
  navLinks?: InputMaybe<Array<InputMaybe<NavbarNavLinksMutation>>>;
  socialLinks?: InputMaybe<Array<InputMaybe<NavbarSocialLinksMutation>>>;
  ctaText?: InputMaybe<Scalars['String']['input']>;
  ctaLink?: InputMaybe<Scalars['String']['input']>;
};

export type FooterQuickLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type FooterLegalLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type FooterMutation = {
  description?: InputMaybe<Scalars['String']['input']>;
  quickLinks?: InputMaybe<Array<InputMaybe<FooterQuickLinksMutation>>>;
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  copyright?: InputMaybe<Scalars['String']['input']>;
  legalLinks?: InputMaybe<Array<InputMaybe<FooterLegalLinksMutation>>>;
};

export type EventsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  images?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type Event_SectionsMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  start?: InputMaybe<Scalars['String']['input']>;
  end?: InputMaybe<Scalars['String']['input']>;
  footer?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type HomeStatsFilter = {
  value?: StringFilter | null | undefined;
  label?: StringFilter | null | undefined;
  icon?: StringFilter | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type HomeClientsFilter = {
  name?: StringFilter | null | undefined;
  logo?: ImageFilter | null | undefined;
};

export type HomeFilter = {
  heroEyebrow?: StringFilter | null | undefined;
  heroTitle1?: StringFilter | null | undefined;
  heroTitleHighlight?: StringFilter | null | undefined;
  heroTitle2?: StringFilter | null | undefined;
  heroDescription?: StringFilter | null | undefined;
  heroPrimaryButton?: StringFilter | null | undefined;
  heroSecondaryButton?: StringFilter | null | undefined;
  stats?: HomeStatsFilter | null | undefined;
  clienteleEyebrow?: StringFilter | null | undefined;
  clienteleTitle?: StringFilter | null | undefined;
  clients?: HomeClientsFilter | null | undefined;
};

export type AboutFilter = {
  eyebrow?: StringFilter | null | undefined;
  title1?: StringFilter | null | undefined;
  titleHighlight?: StringFilter | null | undefined;
  title2?: StringFilter | null | undefined;
  paragraph1?: StringFilter | null | undefined;
  paragraph2?: StringFilter | null | undefined;
  paragraph3?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
};

export type ContactContactCardsFilter = {
  icon?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  lines?: StringFilter | null | undefined;
};

export type ContactStatsFilter = {
  icon?: StringFilter | null | undefined;
  value?: StringFilter | null | undefined;
  label?: StringFilter | null | undefined;
};

export type ContactFilter = {
  eyebrow?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  titleHighlight?: StringFilter | null | undefined;
  subtitle?: StringFilter | null | undefined;
  mapUrl?: StringFilter | null | undefined;
  contactCards?: ContactContactCardsFilter | null | undefined;
  footerText1?: StringFilter | null | undefined;
  footerText2?: StringFilter | null | undefined;
  stats?: ContactStatsFilter | null | undefined;
};

export type GalleryImagesFilter = {
  image?: ImageFilter | null | undefined;
  thumb?: ImageFilter | null | undefined;
  alt?: StringFilter | null | undefined;
};

export type GalleryFilter = {
  eyebrow?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  images?: GalleryImagesFilter | null | undefined;
};

export type ModelsModelsFilter = {
  name?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
};

export type ModelsFilter = {
  eyebrow?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  ctaText?: StringFilter | null | undefined;
  ctaLink?: StringFilter | null | undefined;
  models?: ModelsModelsFilter | null | undefined;
};

export type NavbarNavLinksFilter = {
  name?: StringFilter | null | undefined;
  path?: StringFilter | null | undefined;
};

export type NavbarSocialLinksFilter = {
  platform?: StringFilter | null | undefined;
  url?: StringFilter | null | undefined;
};

export type NavbarFilter = {
  navLinks?: NavbarNavLinksFilter | null | undefined;
  socialLinks?: NavbarSocialLinksFilter | null | undefined;
  ctaText?: StringFilter | null | undefined;
  ctaLink?: StringFilter | null | undefined;
};

export type FooterQuickLinksFilter = {
  label?: StringFilter | null | undefined;
  url?: StringFilter | null | undefined;
};

export type FooterLegalLinksFilter = {
  label?: StringFilter | null | undefined;
  url?: StringFilter | null | undefined;
};

export type FooterFilter = {
  description?: StringFilter | null | undefined;
  quickLinks?: FooterQuickLinksFilter | null | undefined;
  email?: StringFilter | null | undefined;
  phone?: StringFilter | null | undefined;
  location?: StringFilter | null | undefined;
  copyright?: StringFilter | null | undefined;
  legalLinks?: FooterLegalLinksFilter | null | undefined;
};

export type EventsFilter = {
  title?: StringFilter | null | undefined;
  subtitle?: StringFilter | null | undefined;
  images?: ImageFilter | null | undefined;
};

export type Event_SectionsFilter = {
  eyebrow?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  start?: StringFilter | null | undefined;
  end?: StringFilter | null | undefined;
  footer?: StringFilter | null | undefined;
  items?: StringFilter | null | undefined;
};

export type HomePartsFragment = { __typename: 'Home', heroEyebrow: string | null, heroTitle1: string | null, heroTitleHighlight: string | null, heroTitle2: string | null, heroDescription: string | null, heroPrimaryButton: string | null, heroSecondaryButton: string | null, clienteleEyebrow: string | null, clienteleTitle: string | null, stats: Array<{ __typename: 'HomeStats', value: string | null, label: string | null, icon: string | null } | null> | null, clients: Array<{ __typename: 'HomeClients', name: string | null, logo: string | null } | null> | null };

export type AboutPartsFragment = { __typename: 'About', eyebrow: string | null, title1: string | null, titleHighlight: string | null, title2: string | null, paragraph1: string | null, paragraph2: string | null, paragraph3: string | null, image: string | null };

export type ContactPartsFragment = { __typename: 'Contact', eyebrow: string | null, title: string | null, titleHighlight: string | null, subtitle: string | null, mapUrl: string | null, footerText1: string | null, footerText2: string | null, contactCards: Array<{ __typename: 'ContactContactCards', icon: string | null, title: string | null, lines: Array<string | null> | null } | null> | null, stats: Array<{ __typename: 'ContactStats', icon: string | null, value: string | null, label: string | null } | null> | null };

export type GalleryPartsFragment = { __typename: 'Gallery', eyebrow: string | null, title: string | null, images: Array<{ __typename: 'GalleryImages', image: string | null, thumb: string | null, alt: string | null } | null> | null };

export type ModelsPartsFragment = { __typename: 'Models', eyebrow: string | null, title: string | null, description: string | null, ctaText: string | null, ctaLink: string | null, models: Array<{ __typename: 'ModelsModels', name: string | null, title: string | null, image: string | null } | null> | null };

export type NavbarPartsFragment = { __typename: 'Navbar', ctaText: string | null, ctaLink: string | null, navLinks: Array<{ __typename: 'NavbarNavLinks', name: string | null, path: string | null } | null> | null, socialLinks: Array<{ __typename: 'NavbarSocialLinks', platform: string | null, url: string | null } | null> | null };

export type FooterPartsFragment = { __typename: 'Footer', description: string | null, email: string | null, phone: string | null, location: string | null, copyright: string | null, quickLinks: Array<{ __typename: 'FooterQuickLinks', label: string | null, url: string | null } | null> | null, legalLinks: Array<{ __typename: 'FooterLegalLinks', label: string | null, url: string | null } | null> | null };

export type EventsPartsFragment = { __typename: 'Events', title: string, subtitle: string | null, images: Array<string | null> | null };

export type Event_SectionsPartsFragment = { __typename: 'Event_sections', eyebrow: string | null, title: string, description: string | null, start: string | null, end: string | null, footer: string | null, items: Array<string | null> | null };

export type HomeQueryVariables = Exact<{
  relativePath: string;
}>;


export type HomeQuery = { home: { __typename: 'Home', id: string, heroEyebrow: string | null, heroTitle1: string | null, heroTitleHighlight: string | null, heroTitle2: string | null, heroDescription: string | null, heroPrimaryButton: string | null, heroSecondaryButton: string | null, clienteleEyebrow: string | null, clienteleTitle: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stats: Array<{ __typename: 'HomeStats', value: string | null, label: string | null, icon: string | null } | null> | null, clients: Array<{ __typename: 'HomeClients', name: string | null, logo: string | null } | null> | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: HomeFilter | null | undefined;
}>;


export type HomeConnectionQuery = { homeConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Home', id: string, heroEyebrow: string | null, heroTitle1: string | null, heroTitleHighlight: string | null, heroTitle2: string | null, heroDescription: string | null, heroPrimaryButton: string | null, heroSecondaryButton: string | null, clienteleEyebrow: string | null, clienteleTitle: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stats: Array<{ __typename: 'HomeStats', value: string | null, label: string | null, icon: string | null } | null> | null, clients: Array<{ __typename: 'HomeClients', name: string | null, logo: string | null } | null> | null } | null } | null> | null } };

export type AboutQueryVariables = Exact<{
  relativePath: string;
}>;


export type AboutQuery = { about: { __typename: 'About', id: string, eyebrow: string | null, title1: string | null, titleHighlight: string | null, title2: string | null, paragraph1: string | null, paragraph2: string | null, paragraph3: string | null, image: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type AboutConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: AboutFilter | null | undefined;
}>;


export type AboutConnectionQuery = { aboutConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'About', id: string, eyebrow: string | null, title1: string | null, titleHighlight: string | null, title2: string | null, paragraph1: string | null, paragraph2: string | null, paragraph3: string | null, image: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ContactQueryVariables = Exact<{
  relativePath: string;
}>;


export type ContactQuery = { contact: { __typename: 'Contact', id: string, eyebrow: string | null, title: string | null, titleHighlight: string | null, subtitle: string | null, mapUrl: string | null, footerText1: string | null, footerText2: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, contactCards: Array<{ __typename: 'ContactContactCards', icon: string | null, title: string | null, lines: Array<string | null> | null } | null> | null, stats: Array<{ __typename: 'ContactStats', icon: string | null, value: string | null, label: string | null } | null> | null } };

export type ContactConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: ContactFilter | null | undefined;
}>;


export type ContactConnectionQuery = { contactConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Contact', id: string, eyebrow: string | null, title: string | null, titleHighlight: string | null, subtitle: string | null, mapUrl: string | null, footerText1: string | null, footerText2: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, contactCards: Array<{ __typename: 'ContactContactCards', icon: string | null, title: string | null, lines: Array<string | null> | null } | null> | null, stats: Array<{ __typename: 'ContactStats', icon: string | null, value: string | null, label: string | null } | null> | null } | null } | null> | null } };

export type GalleryQueryVariables = Exact<{
  relativePath: string;
}>;


export type GalleryQuery = { gallery: { __typename: 'Gallery', id: string, eyebrow: string | null, title: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, images: Array<{ __typename: 'GalleryImages', image: string | null, thumb: string | null, alt: string | null } | null> | null } };

export type GalleryConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: GalleryFilter | null | undefined;
}>;


export type GalleryConnectionQuery = { galleryConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Gallery', id: string, eyebrow: string | null, title: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, images: Array<{ __typename: 'GalleryImages', image: string | null, thumb: string | null, alt: string | null } | null> | null } | null } | null> | null } };

export type ModelsQueryVariables = Exact<{
  relativePath: string;
}>;


export type ModelsQuery = { models: { __typename: 'Models', id: string, eyebrow: string | null, title: string | null, description: string | null, ctaText: string | null, ctaLink: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, models: Array<{ __typename: 'ModelsModels', name: string | null, title: string | null, image: string | null } | null> | null } };

export type ModelsConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: ModelsFilter | null | undefined;
}>;


export type ModelsConnectionQuery = { modelsConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Models', id: string, eyebrow: string | null, title: string | null, description: string | null, ctaText: string | null, ctaLink: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, models: Array<{ __typename: 'ModelsModels', name: string | null, title: string | null, image: string | null } | null> | null } | null } | null> | null } };

export type NavbarQueryVariables = Exact<{
  relativePath: string;
}>;


export type NavbarQuery = { navbar: { __typename: 'Navbar', id: string, ctaText: string | null, ctaLink: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, navLinks: Array<{ __typename: 'NavbarNavLinks', name: string | null, path: string | null } | null> | null, socialLinks: Array<{ __typename: 'NavbarSocialLinks', platform: string | null, url: string | null } | null> | null } };

export type NavbarConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: NavbarFilter | null | undefined;
}>;


export type NavbarConnectionQuery = { navbarConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Navbar', id: string, ctaText: string | null, ctaLink: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, navLinks: Array<{ __typename: 'NavbarNavLinks', name: string | null, path: string | null } | null> | null, socialLinks: Array<{ __typename: 'NavbarSocialLinks', platform: string | null, url: string | null } | null> | null } | null } | null> | null } };

export type FooterQueryVariables = Exact<{
  relativePath: string;
}>;


export type FooterQuery = { footer: { __typename: 'Footer', id: string, description: string | null, email: string | null, phone: string | null, location: string | null, copyright: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, quickLinks: Array<{ __typename: 'FooterQuickLinks', label: string | null, url: string | null } | null> | null, legalLinks: Array<{ __typename: 'FooterLegalLinks', label: string | null, url: string | null } | null> | null } };

export type FooterConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: FooterFilter | null | undefined;
}>;


export type FooterConnectionQuery = { footerConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Footer', id: string, description: string | null, email: string | null, phone: string | null, location: string | null, copyright: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, quickLinks: Array<{ __typename: 'FooterQuickLinks', label: string | null, url: string | null } | null> | null, legalLinks: Array<{ __typename: 'FooterLegalLinks', label: string | null, url: string | null } | null> | null } | null } | null> | null } };

export type EventsQueryVariables = Exact<{
  relativePath: string;
}>;


export type EventsQuery = { events: { __typename: 'Events', id: string, title: string, subtitle: string | null, images: Array<string | null> | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type EventsConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: EventsFilter | null | undefined;
}>;


export type EventsConnectionQuery = { eventsConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Events', id: string, title: string, subtitle: string | null, images: Array<string | null> | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Event_SectionsQueryVariables = Exact<{
  relativePath: string;
}>;


export type Event_SectionsQuery = { event_sections: { __typename: 'Event_sections', id: string, eyebrow: string | null, title: string, description: string | null, start: string | null, end: string | null, footer: string | null, items: Array<string | null> | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Event_SectionsConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: Event_SectionsFilter | null | undefined;
}>;


export type Event_SectionsConnectionQuery = { event_sectionsConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Event_sections', id: string, eyebrow: string | null, title: string, description: string | null, start: string | null, end: string | null, footer: string | null, items: Array<string | null> | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  heroEyebrow
  heroTitle1
  heroTitleHighlight
  heroTitle2
  heroDescription
  heroPrimaryButton
  heroSecondaryButton
  stats {
    __typename
    value
    label
    icon
  }
  clienteleEyebrow
  clienteleTitle
  clients {
    __typename
    name
    logo
  }
}
    `;
export const AboutPartsFragmentDoc = gql`
    fragment AboutParts on About {
  __typename
  eyebrow
  title1
  titleHighlight
  title2
  paragraph1
  paragraph2
  paragraph3
  image
}
    `;
export const ContactPartsFragmentDoc = gql`
    fragment ContactParts on Contact {
  __typename
  eyebrow
  title
  titleHighlight
  subtitle
  mapUrl
  contactCards {
    __typename
    icon
    title
    lines
  }
  footerText1
  footerText2
  stats {
    __typename
    icon
    value
    label
  }
}
    `;
export const GalleryPartsFragmentDoc = gql`
    fragment GalleryParts on Gallery {
  __typename
  eyebrow
  title
  images {
    __typename
    image
    thumb
    alt
  }
}
    `;
export const ModelsPartsFragmentDoc = gql`
    fragment ModelsParts on Models {
  __typename
  eyebrow
  title
  description
  ctaText
  ctaLink
  models {
    __typename
    name
    title
    image
  }
}
    `;
export const NavbarPartsFragmentDoc = gql`
    fragment NavbarParts on Navbar {
  __typename
  navLinks {
    __typename
    name
    path
  }
  socialLinks {
    __typename
    platform
    url
  }
  ctaText
  ctaLink
}
    `;
export const FooterPartsFragmentDoc = gql`
    fragment FooterParts on Footer {
  __typename
  description
  quickLinks {
    __typename
    label
    url
  }
  email
  phone
  location
  copyright
  legalLinks {
    __typename
    label
    url
  }
}
    `;
export const EventsPartsFragmentDoc = gql`
    fragment EventsParts on Events {
  __typename
  title
  subtitle
  images
}
    `;
export const Event_SectionsPartsFragmentDoc = gql`
    fragment Event_sectionsParts on Event_sections {
  __typename
  eyebrow
  title
  description
  start
  end
  footer
  items
}
    `;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const AboutDocument = gql`
    query about($relativePath: String!) {
  about(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutParts
  }
}
    ${AboutPartsFragmentDoc}`;
export const AboutConnectionDocument = gql`
    query aboutConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutFilter) {
  aboutConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutParts
      }
    }
  }
}
    ${AboutPartsFragmentDoc}`;
export const ContactDocument = gql`
    query contact($relativePath: String!) {
  contact(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactParts
  }
}
    ${ContactPartsFragmentDoc}`;
export const ContactConnectionDocument = gql`
    query contactConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactFilter) {
  contactConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactParts
      }
    }
  }
}
    ${ContactPartsFragmentDoc}`;
export const GalleryDocument = gql`
    query gallery($relativePath: String!) {
  gallery(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GalleryParts
  }
}
    ${GalleryPartsFragmentDoc}`;
export const GalleryConnectionDocument = gql`
    query galleryConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GalleryFilter) {
  galleryConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GalleryParts
      }
    }
  }
}
    ${GalleryPartsFragmentDoc}`;
export const ModelsDocument = gql`
    query models($relativePath: String!) {
  models(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ModelsParts
  }
}
    ${ModelsPartsFragmentDoc}`;
export const ModelsConnectionDocument = gql`
    query modelsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ModelsFilter) {
  modelsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ModelsParts
      }
    }
  }
}
    ${ModelsPartsFragmentDoc}`;
export const NavbarDocument = gql`
    query navbar($relativePath: String!) {
  navbar(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NavbarParts
  }
}
    ${NavbarPartsFragmentDoc}`;
export const NavbarConnectionDocument = gql`
    query navbarConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NavbarFilter) {
  navbarConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NavbarParts
      }
    }
  }
}
    ${NavbarPartsFragmentDoc}`;
export const FooterDocument = gql`
    query footer($relativePath: String!) {
  footer(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FooterParts
  }
}
    ${FooterPartsFragmentDoc}`;
export const FooterConnectionDocument = gql`
    query footerConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FooterFilter) {
  footerConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FooterParts
      }
    }
  }
}
    ${FooterPartsFragmentDoc}`;
export const EventsDocument = gql`
    query events($relativePath: String!) {
  events(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EventsParts
  }
}
    ${EventsPartsFragmentDoc}`;
export const EventsConnectionDocument = gql`
    query eventsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EventsFilter) {
  eventsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EventsParts
      }
    }
  }
}
    ${EventsPartsFragmentDoc}`;
export const Event_SectionsDocument = gql`
    query event_sections($relativePath: String!) {
  event_sections(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Event_sectionsParts
  }
}
    ${Event_SectionsPartsFragmentDoc}`;
export const Event_SectionsConnectionDocument = gql`
    query event_sectionsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Event_sectionsFilter) {
  event_sectionsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Event_sectionsParts
      }
    }
  }
}
    ${Event_SectionsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    about(variables: AboutQueryVariables, options?: C): Promise<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}> {
        return requester<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}, AboutQueryVariables>(AboutDocument, variables, options);
      },
    aboutConnection(variables?: AboutConnectionQueryVariables, options?: C): Promise<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}> {
        return requester<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}, AboutConnectionQueryVariables>(AboutConnectionDocument, variables, options);
      },
    contact(variables: ContactQueryVariables, options?: C): Promise<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}> {
        return requester<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}, ContactQueryVariables>(ContactDocument, variables, options);
      },
    contactConnection(variables?: ContactConnectionQueryVariables, options?: C): Promise<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}> {
        return requester<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}, ContactConnectionQueryVariables>(ContactConnectionDocument, variables, options);
      },
    gallery(variables: GalleryQueryVariables, options?: C): Promise<{data: GalleryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryQueryVariables, query: string}> {
        return requester<{data: GalleryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryQueryVariables, query: string}, GalleryQueryVariables>(GalleryDocument, variables, options);
      },
    galleryConnection(variables?: GalleryConnectionQueryVariables, options?: C): Promise<{data: GalleryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryConnectionQueryVariables, query: string}> {
        return requester<{data: GalleryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryConnectionQueryVariables, query: string}, GalleryConnectionQueryVariables>(GalleryConnectionDocument, variables, options);
      },
    models(variables: ModelsQueryVariables, options?: C): Promise<{data: ModelsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ModelsQueryVariables, query: string}> {
        return requester<{data: ModelsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ModelsQueryVariables, query: string}, ModelsQueryVariables>(ModelsDocument, variables, options);
      },
    modelsConnection(variables?: ModelsConnectionQueryVariables, options?: C): Promise<{data: ModelsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ModelsConnectionQueryVariables, query: string}> {
        return requester<{data: ModelsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ModelsConnectionQueryVariables, query: string}, ModelsConnectionQueryVariables>(ModelsConnectionDocument, variables, options);
      },
    navbar(variables: NavbarQueryVariables, options?: C): Promise<{data: NavbarQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavbarQueryVariables, query: string}> {
        return requester<{data: NavbarQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavbarQueryVariables, query: string}, NavbarQueryVariables>(NavbarDocument, variables, options);
      },
    navbarConnection(variables?: NavbarConnectionQueryVariables, options?: C): Promise<{data: NavbarConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavbarConnectionQueryVariables, query: string}> {
        return requester<{data: NavbarConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavbarConnectionQueryVariables, query: string}, NavbarConnectionQueryVariables>(NavbarConnectionDocument, variables, options);
      },
    footer(variables: FooterQueryVariables, options?: C): Promise<{data: FooterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterQueryVariables, query: string}> {
        return requester<{data: FooterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterQueryVariables, query: string}, FooterQueryVariables>(FooterDocument, variables, options);
      },
    footerConnection(variables?: FooterConnectionQueryVariables, options?: C): Promise<{data: FooterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterConnectionQueryVariables, query: string}> {
        return requester<{data: FooterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterConnectionQueryVariables, query: string}, FooterConnectionQueryVariables>(FooterConnectionDocument, variables, options);
      },
    events(variables: EventsQueryVariables, options?: C): Promise<{data: EventsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsQueryVariables, query: string}> {
        return requester<{data: EventsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsQueryVariables, query: string}, EventsQueryVariables>(EventsDocument, variables, options);
      },
    eventsConnection(variables?: EventsConnectionQueryVariables, options?: C): Promise<{data: EventsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsConnectionQueryVariables, query: string}> {
        return requester<{data: EventsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsConnectionQueryVariables, query: string}, EventsConnectionQueryVariables>(EventsConnectionDocument, variables, options);
      },
    event_sections(variables: Event_SectionsQueryVariables, options?: C): Promise<{data: Event_SectionsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Event_SectionsQueryVariables, query: string}> {
        return requester<{data: Event_SectionsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Event_SectionsQueryVariables, query: string}, Event_SectionsQueryVariables>(Event_SectionsDocument, variables, options);
      },
    event_sectionsConnection(variables?: Event_SectionsConnectionQueryVariables, options?: C): Promise<{data: Event_SectionsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Event_SectionsConnectionQueryVariables, query: string}> {
        return requester<{data: Event_SectionsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Event_SectionsConnectionQueryVariables, query: string}, Event_SectionsConnectionQueryVariables>(Event_SectionsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  